// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Demo$ReasonTemplate = require("./demo.js");

var arg = "demo msg: " + Demo$ReasonTemplate.msg;

exports.arg = arg;
/* No side effect */
